pulibrary/aspace_helpers

helper_methods.rb
used by any methods that need to access a paginated endpoint
=> pagination methods 

helper_methods.rb, usage_examples.rb
add a method to retrieve a single archival object by its former EAD component id; add usage examples
=> Components and usage

reports/get_events_lacking_agents.rb, reports/get_orphaned_events.rb, usage_examples.rb
to aid in identification of linked resources
=> report out select fields from orphaned event records 

helper_methods.rb, usage_examples.rb
also fixed variable scope in a previous method
=> add method and usage example to get resource record by eadid

data_fixes/unnest_boxes/get_nested_boxes.rb, helper_methods.rb, test.rb
=> Nested boxes

data_fixes/unnest_boxes/get_nested_boxes.rb
supports filtering on container type to filter out legitimate nesting scenarios
=> adding API call to top_containers to get type and indicator properties

data_fixes/unnest_boxes/delete_nested_boxes.rb, data_fixes/unnest_boxes/find_multiple_boxes.xquery, data_fixes/unnest_boxes/recreate_nested_boxes.rb, test.rb
still need to compare the two programmatically to be sure we can recreate lost containers from the migrated EADs
=> get output from ASpace and migrated EADs

tools/ead2csv.xquery
now runs over ASpace EAD output
=> updated tool to support digitization workflows post-migration

data_fixes/AC1609/C1609.EAD.xml, data_fixes/AC1609/C1609_top_containers.xml
keeping in case there is follow-up
=> output files for import after applying XQuery routines from migration

data_fixes/add_access_restrictions/fix_missing_restriction_type.rb, data_fixes/remove_ao_restrictions/production/get_restrictions2input.rb, data_fixes/remove_ao_restrictions/production/remove_restrictions.rb, reports/plain_vanilla_report_templates/containers_and_restrictions.rb
I accidentally pushed the updated templates file to this branch also
=> Restrictions stragglers

csv_aspace_runner.rb, data_fixes/change_restriction/update_end_date.rb, helper_methods.rb
read in a CSV with rows for each ASpace record, update record based on CSV, post record back to ASpace, write log
=> class-ifying repeated code

helper_methods.rb
needed in the context of troubleshooting credential and connection errors; closes #160
=> add a method to retrieve user information

reports/plain_vanilla_report_templates/get_MARCxml.rb
=> add method to normalize linebreaks; fix @; add 982 as last (not after a specific field that may not exist)

README.md
I found this workshop document really helpful for getting my bearings.
=> Add a link to the workshop

reports/plain_vanilla_report_templates/get_MARCxml.rb
my bad, this is needed after all!
=> reinstate active_support

reports/aspace2alma/get_MARCxml.rb
exclude C0140 from this process; closes #183
=> Aspace2alma

reports/unpublished_descendants/get_unpublished_descendants.rb
=> get unpublished archival objects of a published resource

helper_methods.rb
this will be run with all future update routines to create a running record of changes to the data
=> add method to create revision statement

helper_methods.rb
=> remove extra comma; remove repository (not needed)

reports/aspace2alma/get_MARCxml.rb
=> add new location prefix to aspace2alma

reports/subject_remediation/get_subjects.rb
=> full SH report; closes #290

data_fixes/AC107/get_barcode.rb, reports/ReCAP_project/get_scamss.rb, reports/ReCAP_project/scamss_top_containers.rb
This comes out of https://github.com/PrincetonUniversityLibrary/lib_reports/issues/239
=> report out extent information for scamss location in repo 5

data_fixes/change_restriction/edit_unitdate.rb, data_fixes/change_restriction/fix_restriction.rb
=> Restrictions

reports/scopecontent/get_scopecontent_collection.rb
=> Scopecontent

data_fixes/edit_phystech/add_boilerplate.rb, data_fixes/edit_phystech/get_index.rb, data_fixes/edit_phystech/replace_phystech.rb
Two routines to accomplish https://github.com/pulibrary/aspace_helpers/issues/374
=> replace, delete, and add phystech notes

reports/aspace2alma/get_MARCxml.rb, spec/reports/aspace2alma/get_MARCxml_spec.rb
=> rename file earlier and write items to log

reports/aspace2alma/get_MARCxml.rb
Co-authored-by: Jane Sandberg <sandbergja@users.noreply.github.com>
=> give method access to log_out

reports/aspace2alma/delete_from_sftp.rb
=> call the method and log errors to file

reports/aspace2alma/get_MARCxml.rb
Co-authored-by: Twade968@users.noreply.github.com
=> for viaf headings, suppress $2; change ind2 to 0; change $0 to $1

data_fixes/edit_accessrestrict/edit_accessrestrict.rb
=> update eng access notes

data_fixes/C1449/edit_accessrestrict.rb
=> reword around the apostrophe and add a revision statement

tools/get_schemata.rb
=> get a csv representation of all ASpace objects

reports/agents/get_all_agents.rb
=> get authority information for all agent records

data_fixes/agents_remediation/subjects2existing_agent.rb
=> replace subject link with existing agent link

data_fixes/agents_remediation/person2new_family_agent.rb
=> construct a family record from a person record; link to descriptive object; delete person record

helper_methods.rb, reports/C0140/get_count_of_linked_objects.rb, usage_examples.rb
=> Count links

data_fixes/agents_remediation/delete_agent.rb
=> delete agents from spreadsheet

config/deploy/production.rb, config/deploy/staging.rb, config/schedule.rb
- Only put cron jobs on lib-jobs-prod2
Closes #527
=> Deploy to all servers

reports/top_containers/top_containers_of_type_not_box.rb
=> get all top containers with container type other than 'box'

reports/C0140/accessions.rb
add the general_notes field (stakeholder request)
=> add general_note field

reports/resource_eadids/resources_missing_eadid.rb
=> Resource eadids

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/dependency_upgrade.md, .github/ISSUE_TEMPLATE/maintenance-task.md
Connected to pulibrary/dacs_handbook#170
=> Align with team issue templates, skipping UI-focused ones

reports/aspace2alma/get_MARCxml.rb
=> exclude collection code C0744.06

reports/aspace2alma/get_MARCxml.rb
=> exclude two collection codes from export

data_fixes/agents_remediation/add_agent_fields.rb, helper_methods.rb
=> update person Agent records

.gitignore, .rspec, reports/aspace2alma/get_MARCxml.rb, reports/aspace2alma/resource.rb, spec/reports/aspace2alma/resource_spec.rb
Co-authored by: maxkadel@github.com
=> get a marc-xml record

data_fixes/agents_remediation/add_agent_fields.rb
=> add title field

data_fixes/libweb2/find_libweb2.xquery
=> find links referencing libweb2

.circleci/config.yml, bearer.yml
Connected to https://github.com/pulibrary/dacs_handbook/issues/238
=> Add bearer to CI for security scans

reports/reparative_description/get_s_slur.xquery
=> report out instances of a string with xpath, eadid and aspace uri

data_fixes/add_new_scopenote/add_scopecontent.rb
=> add scopenotes from csv

helper_methods.rb, reports/MC104/get_digital_objects.rb
…add a method to get all digital objects for the repository
Closes #602 .
=> get all digital objects associated with particular resource records; 

reports/digital_objects/digital_objects.rb
=> Digital objects

reports/MC104/get_digital_objects.rb
=> add refid of the linked archival object to the report

reports/aspace2alma/get_MARCxml.rb, reports/aspace2alma/top_container.rb, spec/reports/aspace2alma/top_container_spec.rb
get container data from the top_container record
=> Container class

Gemfile
=> add bcrypt_pbkdf and ed25519 to the main group

reports/aspace2alma/get_MARCxml.rb
=> remove C1296

reports/aspace2alma/get_MARCxml.rb
=> remove WC059, RBD1, RBD1.1 from export

reports/agents/get_local_agents.rb
=> report out local agents for NACO training

reports/aspace2alma/barcode_validation.rb, reports/aspace2alma/get_MARCxml.rb, spec/reports/aspace2alma/barcode_validation_spec.rb, spec/reports/aspace2alma/get_MARCxml_spec.rb, spec/reports/aspace2alma/item_record_constructor_spec.rb
=> Use Alma Set, rather than sftp file, to check for duplicate barcodes
